Test skill model :   0%|                                                                       | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "./train_skills.py", line 412, in <module>
    test_loss, test_s_T_loss, test_a_loss, test_kl_loss, test_diffusion_loss = test(model, train_loader, test_state_decoder = i > start_training_state_decoder_after, test_num=args.test_num)
  File "./train_skills.py", line 82, in test
    for i, (state, clip, selection, operation, reward, terminated, _, in_grid, out_grid, ex_in, ex_out) in pbar:
  File "/home/yunho/anaconda3/envs/ldcq/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/yunho/anaconda3/envs/ldcq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/yunho/anaconda3/envs/ldcq/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/yunho/anaconda3/envs/ldcq/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yunho/anaconda3/envs/ldcq/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yunho/ldcq_arc/LDCQ_for_SOLAR/utils/utils.py", line 412, in __getitem__
    s_T= torch.FloatTensor(trace['next_state'])
KeyError: 'next_state'